modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/Maciej916/Ma-Chat/issues"

[[mods]]
    modId="ma-chat"
    version="${file.jarVersion}"
    displayName="Ma Chat"
    updateJSONURL="https://raw.githubusercontent.com/Maciej916/Ma-Chat/master/update.json"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/ma-chat"
    logoFile="ma-chat.png"
    credits=""
    authors="Statywek (Maciej916)"
    description="Chat manage tools, automessager, custom join messages and more..."

    [[dependencies.ma-chat]]
        modId="forge"
        mandatory=true
        versionRange="[28,)"
        ordering="NONE"
        side="BOTH"

    [[dependencies.ma-chat]]
        modId="minecraft"
        mandatory=true
        versionRange="[1.14.4]"
        ordering="NONE"
        side="BOTH"